/**
 * build-site.js
 *
 * Renders every HTML page, copies static assets, and generates the sharded
 * client-side search index, sitemap.xml and robots.txt into dist/.
 *
 * The search index is sharded by the domain's first character so the browser
 * only downloads the slice it needs, keeping search scalable for large lists.
 */
import fs from "node:fs";
import path from "node:path";

import { SITE_URL } from "../config.js";
import { DIST_DIR, SITE_DIR, ensureDir, writeText, writeJSON } from "./lib/fs-utils.js";
import { buildModel } from "./lib/model.js";
import { generateSitemap } from "./generate-sitemap.js";
import { step, ok, info, fmt, color } from "./lib/log.js";
import {
  homePage,
  listsPage,
  categoryPage,
  searchPage,
  contributePage,
  documentationPage,
  notFoundPage,
} from "./site/pages.js";

/** Recursively copy a directory (files only, no symlinks). */
function copyDir(from, to) {
  if (!fs.existsSync(from)) return;
  ensureDir(to);
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isSymbolicLink()) continue; // never copy symlinks
    if (entry.isDirectory()) copyDir(src, dst);
    else if (entry.isFile()) fs.copyFileSync(src, dst);
  }
}

function shardChar(domain) {
  const ch = domain[0];
  return /[a-z0-9]/.test(ch) ? ch : "_";
}

function buildSearchIndex(model) {
  const shards = new Map(); // char -> [[domain, slug, fileName], ...]
  for (const cat of model.categories) {
    for (const f of cat.files) {
      for (const d of f.domains) {
        const key = shardChar(d);
        if (!shards.has(key)) shards.set(key, []);
        shards.get(key).push([d, cat.slug, f.name]);
      }
    }
  }
  const dir = path.join(DIST_DIR, "search-index");
  ensureDir(dir);
  const chars = [...shards.keys()].sort();
  for (const ch of chars) {
    writeJSON(path.join(dir, `${ch}.json`), shards.get(ch));
  }
  writeJSON(path.join(dir, "manifest.json"), {
    generatedAt: model.generatedAt,
    commit: model.commit,
    chars,
    totalDomains: model.totals.domains,
  });
  return chars.length;
}

function buildSitemap(model) {
  return generateSitemap(model);
}

/**
 * Generate the Cloudflare Pages `_headers` file.
 *
 * A global security policy is applied to every response, then EXACT paths are
 * emitted for each generated list and JSON file. Exact paths are chosen over
 * middle-wildcard patterns because Cloudflare's `_headers` matcher supports
 * exact paths and trailing splats reliably, guaranteeing `text/plain` for the
 * raw lists and `application/json` for metadata.
 */
function buildHeaders(model) {
  const security = [
    "# Generated by build-site.js — do not edit by hand.",
    "# Global security headers for every response.",
    "/*",
    "  X-Content-Type-Options: nosniff",
    "  X-Frame-Options: DENY",
    "  Referrer-Policy: strict-origin-when-cross-origin",
    "  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()",
    "  Content-Security-Policy: default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'",
    "",
    "# Static assets.",
    "/assets/*",
    "  Cache-Control: public, max-age=3600, stale-while-revalidate=86400",
    "",
    "# Search index shards (JSON).",
    "/search-index/*",
    "  Content-Type: application/json; charset=utf-8",
    "  Cache-Control: public, max-age=300, stale-while-revalidate=86400",
    "",
  ];

  const txtBlock = [];
  const jsonBlock = [
    "/lists.json",
    "  Content-Type: application/json; charset=utf-8",
    "  Cache-Control: public, max-age=300, stale-while-revalidate=86400",
    "/stats.json",
    "  Content-Type: application/json; charset=utf-8",
    "  Cache-Control: public, max-age=300, stale-while-revalidate=86400",
  ];

  for (const cat of model.categories) {
    const files = [...cat.files];
    if (cat.fullFile) files.unshift(cat.fullFile);
    for (const f of files) {
      txtBlock.push(
        f.path,
        "  Content-Type: text/plain; charset=utf-8",
        "  Cache-Control: public, max-age=300, stale-while-revalidate=86400"
      );
    }
    jsonBlock.push(
      `/${cat.slug}/index.json`,
      "  Content-Type: application/json; charset=utf-8",
      "  Cache-Control: public, max-age=300, stale-while-revalidate=86400"
    );
  }

  const out =
    security.join("\n") +
    "\n# Raw list files (plain text).\n" +
    txtBlock.join("\n") +
    "\n\n# JSON metadata.\n" +
    jsonBlock.join("\n") +
    "\n";
  writeText(path.join(DIST_DIR, "_headers"), out);
}

export function buildSite(model = buildModel()) {
  step("Building static site");

  // Pages.
  writeText(path.join(DIST_DIR, "index.html"), homePage(model));
  writeText(path.join(DIST_DIR, "lists", "index.html"), listsPage(model));
  writeText(path.join(DIST_DIR, "search", "index.html"), searchPage(model));
  writeText(path.join(DIST_DIR, "contribute", "index.html"), contributePage(model));
  writeText(path.join(DIST_DIR, "documentation", "index.html"), documentationPage(model));
  writeText(path.join(DIST_DIR, "404.html"), notFoundPage());
  for (const cat of model.categories) {
    writeText(path.join(DIST_DIR, cat.slug, "index.html"), categoryPage(cat, model));
  }
  const pageCount = 6 + model.categories.length;
  info(`  ${color.gray("•")} Rendered ${fmt(pageCount)} HTML pages`);

  // Static assets (css/js) and root files (favicon, og image, CF config).
  copyDir(path.join(SITE_DIR, "assets"), path.join(DIST_DIR, "assets"));
  for (const rootFile of ["favicon.svg", "og.svg", "_redirects", ".well-known"]) {
    const src = path.join(SITE_DIR, rootFile);
    if (fs.existsSync(src)) {
      const stat = fs.statSync(src);
      if (stat.isDirectory()) copyDir(src, path.join(DIST_DIR, rootFile));
      else fs.copyFileSync(src, path.join(DIST_DIR, rootFile));
    }
  }
  info(`  ${color.gray("•")} Copied static assets`);

  const shardCount = buildSearchIndex(model);
  info(`  ${color.gray("•")} Search index: ${fmt(shardCount)} shard(s)`);

  const urlCount = buildSitemap(model);
  buildHeaders(model);
  info(`  ${color.gray("•")} sitemap.xml (${fmt(urlCount)} URLs) + robots.txt + _headers`);

  ok("Static site built into dist/.");
  return model;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildSite();
}
